CREATE DATABASE BANCO1;

USE BANCO1;

CREATE TABLE PESSOA
(
	ID_PESSOA INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    NOME VARCHAR (150),
    IDADE VARCHAR(3),
    CPF VARCHAR(14)
);

CREATE TABLE BANCO
(
	ID_BANCO INT PRIMARY KEY,
    NOME_BANCO VARCHAR(200)
);

CREATE TABLE TEM_BANCO
(
	ID_ASSOCIACO INT PRIMARY KEY,
    ID_PESSOA VARCHAR(14),
    ID_BANCO INT
);
/*nova tabela*/
CREATE TABLE EMPRESA
(
	ID_EMPRESA INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(200),
    CNPJ VARCHAR(18),
    SETOR VARCHAR(200),
    CIDADE VARCHAR(50),
    ESTADO VARCHAR(2),
    ENDERECO VARCHAR(400),
    UNIDADE VARCHAR(10)
);

ALTER TABLE TEM_BANCO ADD CONSTRAINT FOREIGN KEY(ID_PESSOA) REFERENCES PESSOA(CPF);
ALTER TABLE TEM_BANCO ADD CONSTRAINT FOREIGN KEY(ID_BANCO) REFERENCES BANCO(ID_BANCO);

SELECT*FROM PESSOA;

DELETE FROM EMPRESA WHERE ID_EMPRESA = 2;

SELECT*FROM EMPRESA;

DELETE FROM EMPRESA WHERE ID_EMPRESA  = 3 
